AVS-421_116 - Start structure and functionality for AsscociatedTaxables
classyllama/ClassyLlama_AvaTax pull request #213
Opened 2018-12-07 02:42 UTC by sjb9774

## Summary
Associated Taxables are used by Gift Wrapping, WEEE Tax, and some 3rd
party extension to allow calculcating tax for orders on items that are
not technically "items" in the Magento sense. This commit begins the
basic functionality of persisting the Associated Taxable information
from the order step so it can be re-transmitted to Avalara at the time
of invoice processing.

### Note
This PR is primarily for getting code review underway while I finish up and test the final bits of functionality, do not merge yet.

2018-12-12 17:55 UTC, rsisco commented
@sjb9774 - Is the "Note" in your PR comment still applicable?

2018-12-12 18:06 UTC, sjb9774 commented
@rsisco Yes, there are still a few specific scenarios I'd like to test that could impact a few places in the code but I think the bulk of the code review would not be affected.

2019-01-29 15:38 UTC, sjb9774 commented on Plugin/Sales/Model/Spi/CreditmemoResource.php
> +                            /** @var AssociatedTaxableInterface[] $taxable */
Should be `$taxables`

2019-01-29 15:38 UTC, sjb9774 commented on Observer/QuoteSubmitSuccessObserver.php
> +        if (!$quote->isVirtual()) {
What happens when a quote _is_ virtual and has quote-level associated taxables?

2019-01-29 15:38 UTC, sjb9774 commented on Plugin/Sales/Model/Spi/InvoiceResource.php
> +                            /** @var AssociatedTaxableInterface[] $taxable */
Should be `$taxables`

2019-01-29 15:38 UTC, sjb9774 commented on Helper/AssociatedTaxable.php
> +        // TODO: Description?
Address or remove this TODO

2019-01-29 15:38 UTC, sjb9774 commented on Model/Tax/AssociatedTaxableRepository.php
> +    public function __construct(
Add docblock

2019-01-29 15:38 UTC, sjb9774 commented on Observer/QuoteSubmitSuccessObserver.php
> +    public function __construct(
Add `$associatedTaxableHelper` to docblock

2019-01-29 15:38 UTC, sjb9774 commented on Model/Tax/Sales/Total/Quote/Tax.php
>       */
Why were any of these new arguments introduced to this file?

2019-01-29 16:45 UTC, erikhansen requested changes
@sjb9774 Per our discussion, I've added a number of items you'll need to address.

2019-01-29 16:45 UTC, erikhansen commented on Api/SearchCriteria/JoinProcessor/Order.php
> +    public function apply(DbCollection $collection)
@sjb9774 Determine if this is still needed.

2019-01-29 16:45 UTC, erikhansen commented on Helper/AssociatedTaxable.php
> +    public function updateData($associatedTaxableData, $storeId)
Change method name to something more specific, clarifying what this method does

2019-01-29 16:45 UTC, erikhansen commented on Model/Tax/AssociatedTaxable.php
> +    public function _construct()
Add DocBlock to this and all methods missing

2019-01-29 16:45 UTC, erikhansen commented on Model/Tax/AssociatedTaxableRepository.php
> +    protected $filterGroupBuilder;
Missing DocBlock

2019-01-29 16:45 UTC, erikhansen commented on Model/Tax/AssociatedTaxableRepository.php
> +    public function getAllAssociatedTaxablesForInvoice($invoiceId)
Combine this method with `getAllAssociatedTaxablesForCreditMemo` and then pass in the type

2019-01-29 16:45 UTC, erikhansen commented on Observer/QuoteSubmitSuccessObserver.php
> +        $quote = $observer->getQuote();
Wrap all of this in a try/catch, where the type you catch is `\Throwable`. Then log the error to the AvaTax logs with a high severity level (may be "critical"?).

2019-01-29 16:45 UTC, erikhansen commented on Observer/QuoteSubmitSuccessObserver.php
> +            $shippingAddress = $quote->getShippingAddress();
Probably need to refactor this to use `\Magento\Quote\Model\Quote::getAllShippingAddresses` to support multiple addresses.

2019-01-29 16:45 UTC, erikhansen commented on Setup/UpgradeSchema.php
> +                ->addColumn(
Move this to below the `order_id` column

2019-01-29 16:45 UTC, erikhansen commented on Plugin/Sales/Model/Spi/CreditmemoResource.php
> +                $itemTaxes = $this->associatedTaxableRepository->getItemAssociatedTaxablesForOrder($order->getId());
Move all of this code into its own method. Wrap with a try/catch block (with error logging).

2019-01-29 16:45 UTC, erikhansen commented on etc/di.xml
> +    <virtualType name="ClassyLlama\AvaTax\Model\Api\SearchCriteria\AssociatedTaxableCollectionProcessor" type="Magento\Framework\Api\SearchCriteria\CollectionProcessor">
Look at removing this code, through line 84

2019-03-15 19:32 UTC, erikhansen commented
For the record, future work on this PR was put on hold, awaiting approval from Avalara to move forward on it. 

Internal task link: AVS-421_116

2019-04-08 19:33 UTC, erikhansen commented
Closing this PR, per [my comment](https://github.com/classyllama/ClassyLlama_AvaTax/issues/207#issuecomment-480974662) in the related issue.

2019-04-08 19:33 UTC, closed without merging